import React from "react"
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { Layout } from "../components/Layout"
import { useSession, signIn, signOut } from 'next-auth/react'
import { GetServerSideProps } from "next"
import { unstable_getServerSession } from "next-auth"
import api from "../libs/api"
import { authOptions } from "./api/auth/[...nextauth]"
import { AuthUser } from "../types/AuthUser"

type Props = {
  loggedUser: AuthUser
}

export default function Home({ loggedUser }: Props) {
  const { data: session } = useSession()

  if (session) {
    return (
      <Layout>
        <div className={styles.container}>
          <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>

          <main>
            <h1>Olá {session.user.name}</h1>
          </main>

        </div>
      </Layout>
    )
  }

  return (
    <Layout>
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main>
          <h1>Deslogado</h1>
        </main>

      </div>
    </Layout>
  )
}

export const getServerSideProps: GetServerSideProps = async (context) => {
  // const session = await unstable_getServerSession(context.req, context.res, authOptions);
  // if (!session) return { redirect: { destination: '/auth/login', permanent: true } }

  const users = await api.getAllUsers()

  return {
    props: {
      // loggedUser: session.user,
      users
    }
  }
}
